# Using https://github.com/sudar/Arduino-Makefile/
# Installed as Debian package: arduino-mk
# 
# Environment variables have to be set (example working if using packages):
#export ARDUINO_DIR=/usr/share/arduino/
#export ARDMK_DIR=/usr/
#export AVR_TOOLS_DIR= # not required if using package

# make project: make
# upload project: make upload

BOARD_TAG    = uno
#ARDUINO_PORT = /dev/cu.usb*

#ARDUINO_LIBS = Ethernet Ethernet/utility SPI

include /usr/share/arduino/Arduino.mk
